INFO _internal.py:87  * Running on http://192.168.128.134:6000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87  * Detected change in '/home/python/Desktop/Flask/Flask_ihome/ihome/api_v1_0/user.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87  * Detected change in '/home/python/Desktop/Flask/Flask_ihome/ihome/api_v1_0/user.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.128.134:6000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87  * Running on http://192.168.128.134:6000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87  * Detected change in '/home/python/Desktop/Flask/Flask_ihome/config.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87  * Running on http://192.168.128.134:6000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87  * Running on http://192.168.128.134:6000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87  * Running on http://192.168.128.134:6001/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:14:13] "GET /api/v1.0/index HTTP/1.1" 500 -
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:14:14] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:14:14] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:14:14] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:14:14] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:14:14] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Running on http://192.168.128.134:6001/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 139-701-281
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:17:45] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87 192.168.128.134 - - [09/Jan/2018 20:17:46] "GET /favicon.ico HTTP/1.1" 404 -
